# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - develop

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Preparation
    displayName: Install all dependencies
    dependsOn: []
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'

        - task: Npm@1
          displayName: 'npm install angular cli'
          inputs:
            command: custom

            verbose: false

            customCommand: 'install @angular/cli -g'

        - task: Npm@1
          displayName: 'npm install packages'
          inputs:
            verbose: false

  # - stage: RunLinters
  #     displayName: Run Linters
  #     dependsOn: [Preparation]
  #     steps:
  #       - task: Npm@1
  #         displayName: 'Running Lint'
  #         inputs:
  #           command: 'custom'
  #           customCommand: 'run lint'

  # - stage: RunTests
  #     displayName: Run Tests
  #     dependsOn: [RunLinters]
  #     steps:
  #       - task: Npm@1
  #         displayName: 'Running Test'
  #         inputs:
  #           command: 'custom'
  #           customCommand: 'run test'

  # - stage: build
  #   dependsOn: [RunTests]
  #   condition: and(succeeded('RunTests'), True))
  #   steps:
  #     - script: 'npm run build:ssr'
  #       displayName: 'build the project'

  #     - task: CopyFiles@2
  #       displayName: 'Copy client to the root/browser'
  #       inputs:
  #         SourceFolder: '$(Build.SourcesDirectory)/dist/clinic/browser'

  #         TargetFolder: '$(Build.ArtifactStagingDirectory)/deploy-dist/browser'

  #     - task: CopyFiles@2
  #       displayName: 'Copy server to the root'
  #       inputs:
  #         SourceFolder: '$(Build.SourcesDirectory)/dist/clinic/server'

  #         TargetFolder: '$(Build.ArtifactStagingDirectory)/deploy-dist'

  # - stage: deploy
  #   - task: AzureRmWebAppDeployment@4
  #     displayName: 'Azure App Service Deploy: website'
  #     inputs:
  #       azureSubscription: myAngularService

  #       WebAppName: angular-ssr

  #       DeployToSlotFlag: true

  #       ResourceGroupName: admin

  #       Package: '$(Build.ArtifactStagingDirectory)/deploy-dist'

  #       GenerateWebConfig: true

  #       WebConfigParameters: '-Handler iisnode -NodeStartFile main.js -appType node'

  #       UseWebDeploy: false

  #       RemoveAdditionalFilesFlag: true
